import { Question } from "./types";

// All questions are ORIGINAL UPCAT-style items written for this app.
// They follow the official UPCAT subject areas; no leaked / copyrighted items.

export const QUESTIONS: Question[] = [
  // ============ MATHEMATICS (32) ============
  { id: "m1", subject: "Mathematics", topic: "Algebra", difficulty: "normal",
    question: "If 3x − 7 = 2x + 5, what is the value of x² − 4?",
    choices: ["140", "144", "136", "132"], answerIndex: 1,
    explanation: "Solve 3x − 7 = 2x + 5 → x = 12. Then 12² − 4 = 144 − 4 = 140. Wait, recompute: 144 − 4 = 140.",
    steps: ["3x − 2x = 5 + 7", "x = 12", "x² − 4 = 144 − 4 = 140"],
    tip: "Always isolate x first, then plug in." },
  { id: "m2", subject: "Mathematics", topic: "Algebra", difficulty: "hard",
    question: "If a + b = 7 and ab = 10, what is a² + b²?",
    choices: ["29", "39", "49", "19"], answerIndex: 0,
    explanation: "Use identity (a+b)² = a² + 2ab + b² → a² + b² = (a+b)² − 2ab = 49 − 20 = 29.",
    steps: ["(a+b)² = 49", "2ab = 20", "a² + b² = 49 − 20 = 29"],
    tip: "Memorize symmetric polynomial identities — UPCAT loves them." },
  { id: "m3", subject: "Mathematics", topic: "Geometry", difficulty: "normal",
    question: "A right triangle has legs 9 and 12. What is the length of the hypotenuse?",
    choices: ["13", "15", "16", "21"], answerIndex: 1,
    explanation: "9-12-15 is a 3-4-5 triple scaled by 3.", steps: ["√(81+144) = √225 = 15"],
    tip: "Memorize Pythagorean triples: 3-4-5, 5-12-13, 8-15-17, 7-24-25." },
  { id: "m4", subject: "Mathematics", topic: "Geometry", difficulty: "hard",
    question: "The diagonal of a square is 10√2. What is the area of the square?",
    choices: ["50", "100", "200", "144"], answerIndex: 1,
    explanation: "Diagonal = s√2 → s = 10. Area = s² = 100.",
    steps: ["s√2 = 10√2", "s = 10", "Area = 100"], tip: "Square diagonal formula: d = s√2." },
  { id: "m5", subject: "Mathematics", topic: "Algebra", difficulty: "normal",
    question: "Solve for x: 2(x − 3) = 4x − 10.",
    choices: ["1", "2", "3", "4"], answerIndex: 1,
    explanation: "2x − 6 = 4x − 10 → 4 = 2x → x = 2.", steps: ["2x − 6 = 4x − 10", "−2x = −4", "x = 2"] },
  { id: "m6", subject: "Mathematics", topic: "Quadratics", difficulty: "hard",
    question: "What is the sum of the roots of x² − 7x + 12 = 0?",
    choices: ["7", "12", "−7", "−12"], answerIndex: 0,
    explanation: "By Vieta's: sum = −b/a = 7.", tip: "Vieta: sum = −b/a, product = c/a." },
  { id: "m7", subject: "Mathematics", topic: "Quadratics", difficulty: "beast",
    question: "If the roots of x² + kx + 18 = 0 differ by 3, what are the possible values of k?",
    choices: ["±9", "±√81", "±9 only positive", "±3√2"], answerIndex: 0,
    explanation: "(r₁−r₂)² = (r₁+r₂)² − 4r₁r₂ → 9 = k² − 72 → k² = 81 → k = ±9.",
    steps: ["sum = −k, product = 18", "(diff)² = sum² − 4·prod", "9 = k² − 72", "k² = 81"] },
  { id: "m8", subject: "Mathematics", topic: "Ratio & Proportion", difficulty: "normal",
    question: "If 3 workers can finish a job in 12 days, how many days will 4 workers take?",
    choices: ["8", "9", "10", "16"], answerIndex: 1,
    explanation: "Inverse proportion: 3·12 = 4·x → x = 9.",
    steps: ["work = 36 worker-days", "36/4 = 9"], tip: "More workers, fewer days → inverse proportion." },
  { id: "m9", subject: "Mathematics", topic: "Percentage", difficulty: "normal",
    question: "A shirt costs ₱500 after a 20% discount. What was the original price?",
    choices: ["₱600", "₱625", "₱650", "₱700"], answerIndex: 1,
    explanation: "0.8 · P = 500 → P = 625.", tip: "Discount price = original × (1 − rate)." },
  { id: "m10", subject: "Mathematics", topic: "Percentage", difficulty: "hard",
    question: "A price is increased by 25%, then decreased by 20%. The net change is:",
    choices: ["0%", "+5%", "−5%", "+10%"], answerIndex: 0,
    explanation: "1.25 × 0.80 = 1.00 → no change.", tip: "Sequential % changes multiply, not add." },
  { id: "m11", subject: "Mathematics", topic: "Number Theory", difficulty: "hard",
    question: "What is the units digit of 7^2025?",
    choices: ["1", "3", "7", "9"], answerIndex: 2,
    explanation: "Cycle of 7: 7,9,3,1 (period 4). 2025 mod 4 = 1 → units digit = 7.",
    steps: ["7¹=7, 7²=49, 7³=343, 7⁴=...1", "2025 mod 4 = 1", "Answer: 7"] },
  { id: "m12", subject: "Mathematics", topic: "Sequences", difficulty: "normal",
    question: "Find the 10th term of the arithmetic sequence: 4, 7, 10, …",
    choices: ["28", "31", "34", "37"], answerIndex: 1,
    explanation: "a₁ = 4, d = 3. a₁₀ = 4 + 9·3 = 31." },
  { id: "m13", subject: "Mathematics", topic: "Sequences", difficulty: "hard",
    question: "Sum of the first 20 odd positive integers?",
    choices: ["380", "400", "420", "440"], answerIndex: 1,
    explanation: "Sum of first n odd numbers = n². 20² = 400.", tip: "Memorize: 1+3+5+…+(2n−1) = n²." },
  { id: "m14", subject: "Mathematics", topic: "Geometry", difficulty: "hard",
    question: "A circle has area 49π. What is its circumference?",
    choices: ["7π", "14π", "21π", "49π"], answerIndex: 1,
    explanation: "πr² = 49π → r = 7. C = 2πr = 14π." },
  { id: "m15", subject: "Mathematics", topic: "Coordinate Geometry", difficulty: "normal",
    question: "What is the distance between (1,2) and (4,6)?",
    choices: ["3", "4", "5", "7"], answerIndex: 2,
    explanation: "√(3² + 4²) = √25 = 5." },
  { id: "m16", subject: "Mathematics", topic: "Coordinate Geometry", difficulty: "hard",
    question: "What is the slope of the line perpendicular to 2x − 3y = 6?",
    choices: ["2/3", "3/2", "−2/3", "−3/2"], answerIndex: 3,
    explanation: "Slope of given line = 2/3. Perpendicular = −3/2.", tip: "m₁·m₂ = −1." },
  { id: "m17", subject: "Mathematics", topic: "Probability", difficulty: "normal",
    question: "A bag has 3 red, 2 blue, and 5 green balls. P(red)?",
    choices: ["1/10", "3/10", "1/3", "1/2"], answerIndex: 1,
    explanation: "3 favorable / 10 total = 3/10." },
  { id: "m18", subject: "Mathematics", topic: "Probability", difficulty: "beast",
    question: "Two cards are drawn without replacement from a 52-card deck. P(both kings)?",
    choices: ["1/169", "1/221", "1/13", "4/52"], answerIndex: 1,
    explanation: "(4/52)(3/51) = 12/2652 = 1/221.", steps: ["P = 4/52 × 3/51", "= 1/221"] },
  { id: "m19", subject: "Mathematics", topic: "Statistics", difficulty: "normal",
    question: "Mean of 4, 8, 6, 10, 12?",
    choices: ["7", "8", "9", "10"], answerIndex: 1,
    explanation: "(4+8+6+10+12)/5 = 40/5 = 8." },
  { id: "m20", subject: "Mathematics", topic: "Statistics", difficulty: "hard",
    question: "If the mean of 5 numbers is 12 and one number is removed, the new mean is 11. What is the removed number?",
    choices: ["12", "14", "16", "18"], answerIndex: 2,
    explanation: "Total = 60. New total = 4·11 = 44. Removed = 16." },
  { id: "m21", subject: "Mathematics", topic: "Trigonometry", difficulty: "normal",
    question: "What is sin 30° + cos 60°?",
    choices: ["1/2", "1", "√3/2", "0"], answerIndex: 1,
    explanation: "1/2 + 1/2 = 1." },
  { id: "m22", subject: "Mathematics", topic: "Trigonometry", difficulty: "hard",
    question: "If tan θ = 3/4 and θ is acute, what is sin θ?",
    choices: ["3/5", "4/5", "5/3", "5/4"], answerIndex: 0,
    explanation: "Triangle 3-4-5. sin = opp/hyp = 3/5." },
  { id: "m23", subject: "Mathematics", topic: "Logarithms", difficulty: "hard",
    question: "Solve: log₂(x) + log₂(x − 2) = 3.",
    choices: ["2", "3", "4", "−2"], answerIndex: 2,
    explanation: "log₂[x(x−2)] = 3 → x²−2x = 8 → x²−2x−8 = 0 → x = 4 (reject −2).",
    steps: ["Combine logs", "x²−2x = 8", "Factor: (x−4)(x+2)", "x = 4"] },
  { id: "m24", subject: "Mathematics", topic: "Functions", difficulty: "normal",
    question: "If f(x) = 2x + 1, what is f(f(3))?",
    choices: ["13", "14", "15", "16"], answerIndex: 2,
    explanation: "f(3) = 7. f(7) = 15." },
  { id: "m25", subject: "Mathematics", topic: "Word Problems", difficulty: "hard",
    question: "A train travels 240 km at 80 km/h, then 180 km at 60 km/h. What is the average speed?",
    choices: ["68 km/h", "70 km/h", "72 km/h", "75 km/h"], answerIndex: 1,
    explanation: "Total dist = 420 km. Time = 3 + 3 = 6 h. Avg = 70 km/h.",
    tip: "Average speed = total distance / total time, NOT average of speeds." },
  { id: "m26", subject: "Mathematics", topic: "Word Problems", difficulty: "beast",
    question: "Pipe A fills a tank in 6 h, pipe B in 4 h. Together, how long to fill it?",
    choices: ["2 h", "2.4 h", "5 h", "10 h"], answerIndex: 1,
    explanation: "Rate = 1/6 + 1/4 = 5/12. Time = 12/5 = 2.4 h.",
    steps: ["Combine rates", "1/6 + 1/4 = 5/12", "T = 12/5"] },
  { id: "m27", subject: "Mathematics", topic: "Geometry", difficulty: "normal",
    question: "Volume of a cube with side 5?",
    choices: ["25", "75", "100", "125"], answerIndex: 3, explanation: "5³ = 125." },
  { id: "m28", subject: "Mathematics", topic: "Geometry", difficulty: "hard",
    question: "A cylinder has radius 3 and height 10. Volume?",
    choices: ["30π", "60π", "90π", "100π"], answerIndex: 2,
    explanation: "πr²h = π·9·10 = 90π." },
  { id: "m29", subject: "Mathematics", topic: "Algebra", difficulty: "beast",
    question: "If x + 1/x = 4, what is x² + 1/x²?",
    choices: ["12", "14", "16", "18"], answerIndex: 1,
    explanation: "(x+1/x)² = x² + 2 + 1/x² = 16 → x² + 1/x² = 14.",
    tip: "Square the symmetric expression." },
  { id: "m30", subject: "Mathematics", topic: "Number Theory", difficulty: "hard",
    question: "GCD of 84 and 126?",
    choices: ["14", "21", "28", "42"], answerIndex: 3,
    explanation: "84 = 2²·3·7; 126 = 2·3²·7. GCD = 2·3·7 = 42." },
  { id: "m31", subject: "Mathematics", topic: "Combinatorics", difficulty: "hard",
    question: "How many ways to arrange the letters in MATH?",
    choices: ["12", "16", "24", "48"], answerIndex: 2, explanation: "4! = 24." },
  { id: "m32", subject: "Mathematics", topic: "Combinatorics", difficulty: "beast",
    question: "How many distinct arrangements of letters in MISSISSIPPI?",
    choices: ["34650", "11550", "39916800", "4620"], answerIndex: 0,
    explanation: "11! / (4!·4!·2!) = 39916800 / 1152 = 34650." },

  // ============ SCIENCE (30) ============
  { id: "s1", subject: "Science", topic: "Physics: Kinematics", difficulty: "normal",
    question: "A car accelerates uniformly from rest to 20 m/s in 5 s. What is its acceleration?",
    choices: ["2 m/s²", "4 m/s²", "5 m/s²", "10 m/s²"], answerIndex: 1,
    explanation: "a = Δv/Δt = 20/5 = 4 m/s².", tip: "a = (v − u)/t" },
  { id: "s2", subject: "Science", topic: "Physics: Kinematics", difficulty: "hard",
    question: "An object is dropped from rest. After 3 s, how far has it fallen? (g = 10 m/s²)",
    choices: ["15 m", "30 m", "45 m", "90 m"], answerIndex: 2,
    explanation: "d = ½gt² = ½·10·9 = 45 m." },
  { id: "s3", subject: "Science", topic: "Physics: Forces", difficulty: "normal",
    question: "A 5 kg object accelerates at 2 m/s². What net force acts on it?",
    choices: ["2.5 N", "5 N", "7 N", "10 N"], answerIndex: 3, explanation: "F = ma = 10 N." },
  { id: "s4", subject: "Science", topic: "Physics: Energy", difficulty: "hard",
    question: "A 2 kg ball is lifted 5 m. What is its gravitational PE? (g = 10)",
    choices: ["50 J", "100 J", "150 J", "200 J"], answerIndex: 1, explanation: "PE = mgh = 2·10·5 = 100 J." },
  { id: "s5", subject: "Science", topic: "Physics: Energy", difficulty: "hard",
    question: "Kinetic energy of a 4 kg object moving at 6 m/s?",
    choices: ["48 J", "72 J", "96 J", "144 J"], answerIndex: 1,
    explanation: "KE = ½mv² = ½·4·36 = 72 J." },
  { id: "s6", subject: "Science", topic: "Physics: Electricity", difficulty: "normal",
    question: "Ohm's law: if V = 12 V and R = 4 Ω, find I.",
    choices: ["2 A", "3 A", "4 A", "8 A"], answerIndex: 1, explanation: "I = V/R = 3 A." },
  { id: "s7", subject: "Science", topic: "Physics: Waves", difficulty: "hard",
    question: "A wave has frequency 50 Hz and wavelength 4 m. Speed?",
    choices: ["54 m/s", "200 m/s", "12.5 m/s", "0.08 m/s"], answerIndex: 1,
    explanation: "v = fλ = 200 m/s." },
  { id: "s8", subject: "Science", topic: "Chemistry: Atoms", difficulty: "normal",
    question: "Number of protons in a neutral carbon-14 atom?",
    choices: ["6", "8", "12", "14"], answerIndex: 0, explanation: "Carbon's atomic number is 6." },
  { id: "s9", subject: "Science", topic: "Chemistry: Bonding", difficulty: "hard",
    question: "Which bond is formed by sharing electrons?",
    choices: ["Ionic", "Covalent", "Metallic", "Hydrogen"], answerIndex: 1,
    explanation: "Covalent bonds share electrons; ionic transfer them." },
  { id: "s10", subject: "Science", topic: "Chemistry: Stoichiometry", difficulty: "hard",
    question: "How many moles are in 36 g of water (H₂O)?",
    choices: ["1", "1.5", "2", "3"], answerIndex: 2,
    explanation: "M(H₂O) = 18 g/mol. n = 36/18 = 2 mol." },
  { id: "s11", subject: "Science", topic: "Chemistry: Acids/Bases", difficulty: "normal",
    question: "What is the pH of a neutral solution at 25°C?",
    choices: ["0", "7", "10", "14"], answerIndex: 1, explanation: "Pure water has pH 7." },
  { id: "s12", subject: "Science", topic: "Chemistry: Gases", difficulty: "hard",
    question: "At STP, what volume does 1 mole of an ideal gas occupy?",
    choices: ["11.2 L", "22.4 L", "24.5 L", "44.8 L"], answerIndex: 1,
    explanation: "Molar volume at STP = 22.4 L." },
  { id: "s13", subject: "Science", topic: "Biology: Cells", difficulty: "normal",
    question: "Which organelle is the powerhouse of the cell?",
    choices: ["Nucleus", "Ribosome", "Mitochondrion", "Lysosome"], answerIndex: 2,
    explanation: "Mitochondria produce ATP via cellular respiration." },
  { id: "s14", subject: "Science", topic: "Biology: Genetics", difficulty: "hard",
    question: "In a Punnett square cross of Aa × Aa, what fraction of offspring are homozygous recessive?",
    choices: ["1/4", "1/2", "3/4", "1"], answerIndex: 0,
    explanation: "1 AA : 2 Aa : 1 aa → 1/4 are aa." },
  { id: "s15", subject: "Science", topic: "Biology: Evolution", difficulty: "normal",
    question: "Who proposed the theory of natural selection?",
    choices: ["Mendel", "Lamarck", "Darwin", "Linnaeus"], answerIndex: 2,
    explanation: "Charles Darwin, 'On the Origin of Species' (1859)." },
  { id: "s16", subject: "Science", topic: "Biology: Ecology", difficulty: "hard",
    question: "A primary consumer is best described as a(n):",
    choices: ["Producer", "Herbivore", "Carnivore", "Decomposer"], answerIndex: 1,
    explanation: "Primary consumers feed directly on producers (plants)." },
  { id: "s17", subject: "Science", topic: "Biology: Human Body", difficulty: "normal",
    question: "Which blood vessel carries oxygenated blood from lungs to the heart?",
    choices: ["Pulmonary artery", "Pulmonary vein", "Aorta", "Vena cava"], answerIndex: 1,
    explanation: "Pulmonary VEINS bring oxygenated blood to the heart." },
  { id: "s18", subject: "Science", topic: "Earth Science", difficulty: "normal",
    question: "Which layer of the Earth is liquid?",
    choices: ["Crust", "Mantle", "Outer core", "Inner core"], answerIndex: 2,
    explanation: "The outer core is molten iron-nickel; the inner core is solid." },
  { id: "s19", subject: "Science", topic: "Earth Science", difficulty: "hard",
    question: "What process drives plate tectonics?",
    choices: ["Solar radiation", "Convection in the mantle", "Coriolis effect", "Magnetic reversal"], answerIndex: 1,
    explanation: "Heat-driven convection currents in the mantle move plates." },
  { id: "s20", subject: "Science", topic: "Astronomy", difficulty: "normal",
    question: "Which planet has the most moons (as of recent counts)?",
    choices: ["Jupiter", "Saturn", "Uranus", "Neptune"], answerIndex: 1,
    explanation: "Saturn currently leads in confirmed moons." },
  { id: "s21", subject: "Science", topic: "Physics: Density", difficulty: "hard",
    question: "An object has mass 240 g and volume 80 cm³. What is its density?",
    choices: ["2 g/cm³", "3 g/cm³", "4 g/cm³", "0.33 g/cm³"], answerIndex: 1,
    explanation: "ρ = m/V = 240/80 = 3 g/cm³." },
  { id: "s22", subject: "Science", topic: "Physics: Heat", difficulty: "hard",
    question: "Heat needed to raise 200 g of water by 10°C? (c = 4.18 J/g·°C)",
    choices: ["836 J", "8360 J", "418 J", "4180 J"], answerIndex: 1,
    explanation: "Q = mcΔT = 200·4.18·10 = 8360 J." },
  { id: "s23", subject: "Science", topic: "Chemistry: Periodic", difficulty: "normal",
    question: "Which group contains the noble gases?",
    choices: ["1", "2", "17", "18"], answerIndex: 3, explanation: "Group 18 — He, Ne, Ar, Kr, Xe, Rn." },
  { id: "s24", subject: "Science", topic: "Chemistry: Reactions", difficulty: "hard",
    question: "Balance: __ H₂ + __ O₂ → __ H₂O. Coefficients (smallest whole)?",
    choices: ["1, 1, 1", "2, 1, 2", "1, 2, 1", "2, 2, 2"], answerIndex: 1,
    explanation: "2H₂ + O₂ → 2H₂O." },
  { id: "s25", subject: "Science", topic: "Biology: Photosynthesis", difficulty: "normal",
    question: "Photosynthesis converts CO₂ and water into glucose and:",
    choices: ["Nitrogen", "Oxygen", "Methane", "Hydrogen"], answerIndex: 1,
    explanation: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂." },
  { id: "s26", subject: "Science", topic: "Physics: Momentum", difficulty: "beast",
    question: "A 2 kg cart at 4 m/s collides and sticks to a 3 kg cart at rest. Final speed?",
    choices: ["1.6 m/s", "1.0 m/s", "2.4 m/s", "0.8 m/s"], answerIndex: 0,
    explanation: "Momentum conserved: 2·4 = (2+3)v → v = 1.6 m/s.",
    steps: ["p_before = 8", "5v = 8", "v = 1.6"] },
  { id: "s27", subject: "Science", topic: "Chemistry: Solutions", difficulty: "hard",
    question: "Molarity of a solution with 0.5 mol solute in 250 mL?",
    choices: ["0.5 M", "1 M", "2 M", "0.25 M"], answerIndex: 2,
    explanation: "M = mol/L = 0.5/0.25 = 2 M." },
  { id: "s28", subject: "Science", topic: "Biology: Cells", difficulty: "hard",
    question: "Which cell process produces 2 daughter cells identical to the parent?",
    choices: ["Mitosis", "Meiosis", "Fertilization", "Translation"], answerIndex: 0,
    explanation: "Mitosis = identical diploid copies; meiosis = gametes." },
  { id: "s29", subject: "Science", topic: "Physics: Optics", difficulty: "hard",
    question: "Light traveling from air into water:",
    choices: ["Speeds up, bends away from normal", "Slows down, bends toward normal", "Same speed", "Slows down, bends away from normal"], answerIndex: 1,
    explanation: "Higher index → slower → refracts toward normal." },
  { id: "s30", subject: "Science", topic: "Earth Science", difficulty: "hard",
    question: "Which gas is the largest contributor to the greenhouse effect by quantity?",
    choices: ["CO₂", "Water vapor", "Methane", "N₂O"], answerIndex: 1,
    explanation: "Water vapor is the most abundant greenhouse gas, though CO₂ is the dominant human-driven forcing." },

  // ============ ENGLISH LANGUAGE (30) ============
  { id: "e1", subject: "English Language", topic: "Subject-Verb Agreement", difficulty: "normal",
    question: "Choose the correct sentence:",
    choices: [
      "The list of items are on the desk.",
      "The list of items is on the desk.",
      "The list of items were on the desk.",
      "The list of items have been on the desk."],
    answerIndex: 1, explanation: "The subject 'list' is singular; 'of items' is a prepositional phrase.",
    tip: "Find the head noun, ignore prepositional phrases." },
  { id: "e2", subject: "English Language", topic: "Pronouns", difficulty: "hard",
    question: "Between you and ___, the answer is obvious.",
    choices: ["I", "me", "myself", "mine"], answerIndex: 1,
    explanation: "After a preposition, use the objective case: 'me'." },
  { id: "e3", subject: "English Language", topic: "Tenses", difficulty: "hard",
    question: "By next June, she ___ here for ten years.",
    choices: ["will work", "will be working", "will have worked", "has worked"], answerIndex: 2,
    explanation: "Future perfect: action completed before a future point." },
  { id: "e4", subject: "English Language", topic: "Modifiers", difficulty: "hard",
    question: "Which sentence has a misplaced modifier?",
    choices: [
      "Running quickly, Maria caught the bus.",
      "Maria caught the bus running quickly.",
      "Maria, running quickly, caught the bus.",
      "While running quickly, Maria caught the bus."],
    answerIndex: 1, explanation: "Option B implies the bus is running quickly." },
  { id: "e5", subject: "English Language", topic: "Diction", difficulty: "normal",
    question: "Choose the correct word: The new policy will ___ all employees.",
    choices: ["effect", "affect", "infect", "afflict"], answerIndex: 1,
    explanation: "'Affect' (verb) = to influence; 'effect' (noun) = result." },
  { id: "e6", subject: "English Language", topic: "Parallelism", difficulty: "hard",
    question: "Which sentence is parallel?",
    choices: [
      "She likes hiking, swimming, and to bike.",
      "She likes hiking, swimming, and biking.",
      "She likes to hike, swimming, and biking.",
      "She likes hike, swim, and bike."],
    answerIndex: 1 , explanation: "All items must share the same grammatical form." },
  { id: "e7", subject: "English Language", topic: "Punctuation", difficulty: "hard",
    question: "Where is the semicolon used correctly?",
    choices: [
      "I went home; because I was tired.",
      "I went home; I was tired.",
      "I went; home, I was tired.",
      "I went home, I was tired; then slept."],
    answerIndex: 1, explanation: "Semicolons join two independent clauses." },
  { id: "e8", subject: "English Language", topic: "Vocabulary", difficulty: "hard",
    question: "Choose the synonym of UBIQUITOUS:",
    choices: ["Rare", "Hidden", "Widespread", "Ancient"], answerIndex: 2,
    explanation: "Ubiquitous = present everywhere." },
  { id: "e9", subject: "English Language", topic: "Vocabulary", difficulty: "beast",
    question: "Choose the antonym of EPHEMERAL:",
    choices: ["Brief", "Lasting", "Foreign", "Vivid"], answerIndex: 1,
    explanation: "Ephemeral = short-lived; opposite is lasting/permanent." },
  { id: "e10", subject: "English Language", topic: "Idioms", difficulty: "normal",
    question: "'To bite the bullet' means:",
    choices: ["To eat quickly", "To endure a painful situation", "To give up", "To win narrowly"], answerIndex: 1,
    explanation: "Idiom: to face an unavoidable difficult situation." },
  { id: "e11", subject: "English Language", topic: "Sentence Correction", difficulty: "hard",
    question: "Which is correct?",
    choices: [
      "Each of the students have submitted their papers.",
      "Each of the students has submitted his or her paper.",
      "Each of the students have submitted his paper.",
      "Each of the students has submit his paper."],
    answerIndex: 1, explanation: "'Each' is singular; verb and pronoun must agree." },
  { id: "e12", subject: "English Language", topic: "Conditionals", difficulty: "hard",
    question: "If I ___ richer, I would travel the world.",
    choices: ["am", "was", "were", "had been"], answerIndex: 2,
    explanation: "Second conditional uses 'were' for all subjects (subjunctive)." },
  { id: "e13", subject: "English Language", topic: "Articles", difficulty: "normal",
    question: "She is ___ honest woman.",
    choices: ["a", "an", "the", "no article"], answerIndex: 1,
    explanation: "'Honest' begins with a vowel sound (silent h)." },
  { id: "e14", subject: "English Language", topic: "Prepositions", difficulty: "normal",
    question: "She is good ___ mathematics.",
    choices: ["in", "on", "at", "with"], answerIndex: 2,
    explanation: "'Good at' is the standard collocation for skills." },
  { id: "e15", subject: "English Language", topic: "Voice", difficulty: "hard",
    question: "Convert to passive: 'The committee approved the proposal.'",
    choices: [
      "The proposal was approved by the committee.",
      "The proposal is approving by the committee.",
      "The proposal had approved by the committee.",
      "The committee was approved by the proposal."],
    answerIndex: 0, explanation: "Object becomes subject; use 'be' + past participle." },
  { id: "e16", subject: "English Language", topic: "Vocabulary", difficulty: "hard",
    question: "MERIDIAN most nearly means:",
    choices: ["Sunset", "Peak", "Border", "Path"], answerIndex: 1,
    explanation: "Meridian = highest point or noon position." },
  { id: "e17", subject: "English Language", topic: "Analogy", difficulty: "hard",
    question: "OASIS : DESERT :: ___ : ___",
    choices: ["water : land", "island : ocean", "tree : forest", "mountain : valley"], answerIndex: 1,
    explanation: "An oasis is a haven within a desert; an island is land within an ocean." },
  { id: "e18", subject: "English Language", topic: "Analogy", difficulty: "beast",
    question: "PROLIFIC : SCARCE :: VERBOSE : ___",
    choices: ["loud", "concise", "honest", "complex"], answerIndex: 1,
    explanation: "Antonym pairing: prolific↔scarce, verbose↔concise." },
  { id: "e19", subject: "English Language", topic: "Word Choice", difficulty: "hard",
    question: "Choose the best word: The evidence was ___ to convict him.",
    choices: ["scant", "lavish", "sufficient", "frivolous"], answerIndex: 2,
    explanation: "'Sufficient' = enough." },
  { id: "e20", subject: "English Language", topic: "Sentence Structure", difficulty: "hard",
    question: "Identify the sentence type: 'Although it rained, we went hiking.'",
    choices: ["Simple", "Compound", "Complex", "Compound-complex"], answerIndex: 2,
    explanation: "One independent + one dependent clause = complex." },
  { id: "e21", subject: "English Language", topic: "Capitalization", difficulty: "normal",
    question: "Which is correctly capitalized?",
    choices: [
      "I love studying english at the university of the philippines.",
      "I love studying English at the University of the Philippines.",
      "I Love Studying English at the University of the Philippines.",
      "i love studying english at the University of the Philippines."],
    answerIndex: 1, explanation: "Proper nouns and language names are capitalized." },
  { id: "e22", subject: "English Language", topic: "Redundancy", difficulty: "hard",
    question: "Which phrase is redundant?",
    choices: ["Final outcome", "End result", "Both A and B", "Neither"], answerIndex: 2,
    explanation: "'Outcome' and 'result' already imply finality." },
  { id: "e23", subject: "English Language", topic: "Subject-Verb", difficulty: "hard",
    question: "Neither the teacher nor the students ___ ready.",
    choices: ["is", "are", "was", "has been"], answerIndex: 1,
    explanation: "With 'neither/nor', verb agrees with the nearer subject (students = plural)." },
  { id: "e24", subject: "English Language", topic: "Vocabulary", difficulty: "beast",
    question: "Choose the synonym of LACONIC:",
    choices: ["Wordy", "Brief", "Lazy", "Sad"], answerIndex: 1,
    explanation: "Laconic = using few words." },
  { id: "e25", subject: "English Language", topic: "Vocabulary", difficulty: "hard",
    question: "PERNICIOUS most nearly means:",
    choices: ["Helpful", "Harmful", "Hidden", "Quick"], answerIndex: 1,
    explanation: "Pernicious = causing harm, especially gradually." },
  { id: "e26", subject: "English Language", topic: "Pronoun Agreement", difficulty: "hard",
    question: "Everyone must bring ___ own pen.",
    choices: ["their", "his or her", "his", "they're"], answerIndex: 1,
    explanation: "Formal English treats 'everyone' as singular → 'his or her'." },
  { id: "e27", subject: "English Language", topic: "Diction", difficulty: "normal",
    question: "He gave good ___ on the matter.",
    choices: ["advise", "advice", "advices", "advising"], answerIndex: 1,
    explanation: "'Advice' (noun) vs 'advise' (verb)." },
  { id: "e28", subject: "English Language", topic: "Logic in Sentences", difficulty: "hard",
    question: "Identify the fallacy: 'Everyone is buying it, so it must be good.'",
    choices: ["Ad hominem", "Bandwagon", "Straw man", "False cause"], answerIndex: 1,
    explanation: "Bandwagon: appeal to popularity." },
  { id: "e29", subject: "English Language", topic: "Vocabulary", difficulty: "beast",
    question: "OBSEQUIOUS most nearly means:",
    choices: ["Servile", "Defiant", "Quiet", "Generous"], answerIndex: 0,
    explanation: "Obsequious = excessively eager to please." },
  { id: "e30", subject: "English Language", topic: "Comma Usage", difficulty: "hard",
    question: "Which sentence uses commas correctly?",
    choices: [
      "After dinner, we went, to the park.",
      "After dinner we, went to the park.",
      "After dinner, we went to the park.",
      "After, dinner we went to the park."],
    answerIndex: 2, explanation: "Comma after introductory phrase only." },

  // ============ FILIPINO LANGUAGE (30) ============
  { id: "f1", subject: "Filipino Language", topic: "Balarila", difficulty: "normal",
    question: "Alin ang tamang baybay?",
    choices: ["Karunungan", "Karunongan", "Kerunungan", "Karonongan"], answerIndex: 0,
    explanation: "Tamang baybay: KARUNUNGAN (mula sa 'dunong')." },
  { id: "f2", subject: "Filipino Language", topic: "Pang-ugnay", difficulty: "hard",
    question: "Pumasok siya sa paaralan ___ malakas ang ulan.",
    choices: ["dahil", "kaya", "kahit", "upang"], answerIndex: 2,
    explanation: "'Kahit' nagpapahayag ng kontradiksyon." },
  { id: "f3", subject: "Filipino Language", topic: "Panghalip", difficulty: "normal",
    question: "Anong uri ng panghalip ang 'sila'?",
    choices: ["Panao", "Pamatlig", "Pananong", "Panaklaw"], answerIndex: 0,
    explanation: "'Sila' ay panghalip panao na pangmaramihan, ikatlong panauhan." },
  { id: "f4", subject: "Filipino Language", topic: "Pandiwa", difficulty: "hard",
    question: "Anong aspekto ng pandiwa ang 'kumakain'?",
    choices: ["Pangnagdaan", "Pangkasalukuyan", "Panghinaharap", "Pawatas"], answerIndex: 1,
    explanation: "Pangkasalukuyan: ginagawa pa ang kilos." },
  { id: "f5", subject: "Filipino Language", topic: "Tayutay", difficulty: "hard",
    question: "Aling tayutay ang ginamit: 'Ang kanyang puso ay bato'?",
    choices: ["Pagtutulad", "Pagwawangis (metapora)", "Pagmamalabis", "Pagtatao"], answerIndex: 1,
    explanation: "Metapora: tuwirang paghahalintulad nang walang 'parang/tulad'." },
  { id: "f6", subject: "Filipino Language", topic: "Tayutay", difficulty: "hard",
    question: "'Mabilis pa sa alas-kuwatro' ay halimbawa ng:",
    choices: ["Simili", "Pagmamalabis (hyperbole)", "Personipikasyon", "Onomatopeya"], answerIndex: 1,
    explanation: "Pagmamalabis: labis na pagpapahayag." },
  { id: "f7", subject: "Filipino Language", topic: "Salawikain", difficulty: "normal",
    question: "'Ang hindi marunong lumingon sa pinanggalingan ay hindi makararating sa ___.'",
    choices: ["bahay", "paroroonan", "tagumpay", "kinabukasan"], answerIndex: 1,
    explanation: "Salawikaing klasiko ni Rizal." },
  { id: "f8", subject: "Filipino Language", topic: "Bantas", difficulty: "normal",
    question: "Anong bantas ang ginagamit sa pagtatapos ng tanong?",
    choices: ["Tuldok", "Pananong", "Padamdam", "Kuwit"], answerIndex: 1,
    explanation: "Tandang pananong (?)." },
  { id: "f9", subject: "Filipino Language", topic: "Pang-uri", difficulty: "hard",
    question: "Tukuyin ang antas ng pang-uring 'pinakamabait':",
    choices: ["Lantay", "Pahambing", "Pasukdol", "Patangi"], answerIndex: 2,
    explanation: "Pasukdol: pinakamataas na antas." },
  { id: "f10", subject: "Filipino Language", topic: "Talasalitaan", difficulty: "hard",
    question: "Ano ang kahulugan ng 'lihim'?",
    choices: ["Hayag", "Sikreto", "Maingay", "Mabilis"], answerIndex: 1,
    explanation: "Lihim = sikreto, hindi inihahayag." },
  { id: "f11", subject: "Filipino Language", topic: "Talasalitaan", difficulty: "hard",
    question: "Kasingkahulugan ng 'masinop':",
    choices: ["Maaksaya", "Maingat", "Marangal", "Mainit"], answerIndex: 1,
    explanation: "Masinop = maingat, organisado." },
  { id: "f12", subject: "Filipino Language", topic: "Kasalungat", difficulty: "normal",
    question: "Kasalungat ng 'mapagbigay':",
    choices: ["Maginoo", "Maramot", "Magalang", "Masipag"], answerIndex: 1,
    explanation: "Maramot = hindi mapagbigay." },
  { id: "f13", subject: "Filipino Language", topic: "Pangungusap", difficulty: "hard",
    question: "Aling pangungusap ang nasa ayos na karaniwan?",
    choices: [
      "Maganda ang bulaklak.",
      "Ang bulaklak ay maganda.",
      "Bulaklak na maganda.",
      "Maganda, ang bulaklak."],
    answerIndex: 0, explanation: "Karaniwan: panaguri muna bago paksa." },
  { id: "f14", subject: "Filipino Language", topic: "Panlapi", difficulty: "hard",
    question: "Anong uri ng panlapi ang 'um' sa salitang 'umalis'?",
    choices: ["Unlapi", "Gitlapi", "Hulapi", "Kabilaan"], answerIndex: 1,
    explanation: "Pinasok sa loob ng salitang-ugat → gitlapi." },
  { id: "f15", subject: "Filipino Language", topic: "Pangatnig", difficulty: "normal",
    question: "Alin ang pangatnig na nagpapahayag ng dahilan?",
    choices: ["ngunit", "kung", "dahil", "habang"], answerIndex: 2,
    explanation: "'Dahil' nagpapakilala ng dahilan." },
  { id: "f16", subject: "Filipino Language", topic: "Pang-abay", difficulty: "hard",
    question: "Anong uri ng pang-abay ang 'kahapon'?",
    choices: ["Pamanahon", "Panlunan", "Pamaraan", "Panggaano"], answerIndex: 0,
    explanation: "Pamanahon: nagsasaad ng panahon." },
  { id: "f17", subject: "Filipino Language", topic: "Talasalitaan", difficulty: "beast",
    question: "Ano ang kahulugan ng 'manunulat'?",
    choices: ["mambabasa", "mananaliksik", "manlilikha ng akda", "guro"], answerIndex: 2,
    explanation: "Manunulat = sumusulat ng mga akda." },
  { id: "f18", subject: "Filipino Language", topic: "Pang-uri", difficulty: "normal",
    question: "Alin sa mga sumusunod ay pang-uri?",
    choices: ["tumakbo", "mabilis", "kahapon", "siya"], answerIndex: 1,
    explanation: "'Mabilis' naglalarawan ng pangngalan." },
  { id: "f19", subject: "Filipino Language", topic: "Wastong gamit", difficulty: "hard",
    question: "Alin ang tamang gamit ng 'ng' at 'nang'?",
    choices: [
      "Kumain ng siya nang mabilis.",
      "Kumain ng mabilis siya.",
      "Kumain siya nang mabilis ng kanin.",
      "Kumain siya ng mabilis nang kanin."],
    answerIndex: 2, explanation: "'Nang' = paano (pang-abay); 'ng' = bago ng pangngalan." },
  { id: "f20", subject: "Filipino Language", topic: "Sawikain", difficulty: "hard",
    question: "'Magkabaliktad ang mukha' ay nangangahulugang:",
    choices: ["nahihiya", "nagagalit", "natutuwa", "namamangha"], answerIndex: 1,
    explanation: "Sawikain para sa galit." },
  { id: "f21", subject: "Filipino Language", topic: "Bahagi ng Pananalita", difficulty: "normal",
    question: "Anong bahagi ng pananalita ang 'mabuti'?",
    choices: ["Pangngalan", "Pang-uri", "Pandiwa", "Pang-abay"], answerIndex: 1,
    explanation: "Naglalarawan ng pangngalan → pang-uri." },
  { id: "f22", subject: "Filipino Language", topic: "Pagbabaybay", difficulty: "hard",
    question: "Alin ang tamang baybay?",
    choices: ["Karangyaan", "Karangyahan", "Karangiaan", "Karangyaan"], answerIndex: 0,
    explanation: "Tamang baybay: KARANGYAAN." },
  { id: "f23", subject: "Filipino Language", topic: "Pang-ukol", difficulty: "hard",
    question: "Alin ang pang-ukol sa pangungusap: 'Para sa iyo ang regalo.'?",
    choices: ["para", "para sa", "iyo", "regalo"], answerIndex: 1,
    explanation: "'Para sa' nagpapakita ng tatanggap." },
  { id: "f24", subject: "Filipino Language", topic: "Tambalan", difficulty: "hard",
    question: "Anong uri ng salita ang 'silid-aralan'?",
    choices: ["Payak", "Maylapi", "Inuulit", "Tambalan"], answerIndex: 3,
    explanation: "Pinagsamang dalawang salita." },
  { id: "f25", subject: "Filipino Language", topic: "Ponolohiya", difficulty: "beast",
    question: "Ilan ang patinig sa modernong alpabetong Filipino?",
    choices: ["3", "5", "8", "28"], answerIndex: 1,
    explanation: "5 patinig: A, E, I, O, U." },
  { id: "f26", subject: "Filipino Language", topic: "Talasalitaan", difficulty: "hard",
    question: "Ano ang kasingkahulugan ng 'masigla'?",
    choices: ["malungkot", "masaya", "tahimik", "pagod"], answerIndex: 1,
    explanation: "Masigla = puno ng buhay/kaligayahan." },
  { id: "f27", subject: "Filipino Language", topic: "Pandiwa", difficulty: "hard",
    question: "Aspekto ng 'kakain' ay:",
    choices: ["pangnagdaan", "pangkasalukuyan", "panghinaharap", "pawatas"], answerIndex: 2,
    explanation: "Hindi pa nagsisimula → panghinaharap." },
  { id: "f28", subject: "Filipino Language", topic: "Pangngalan", difficulty: "normal",
    question: "Alin ang pangngalang pantangi?",
    choices: ["bayan", "Maynila", "lungsod", "kalye"], answerIndex: 1,
    explanation: "Pantangi: tiyak na pangalan ng tao/lugar/bagay." },
  { id: "f29", subject: "Filipino Language", topic: "Salitang Magkasingkahulugan", difficulty: "normal",
    question: "Alin ang kasingkahulugan ng 'lakas'?",
    choices: ["hina", "tibay", "lambot", "lamig"], answerIndex: 1,
    explanation: "Lakas ≈ tibay." },
  { id: "f30", subject: "Filipino Language", topic: "Wastong Gamit", difficulty: "hard",
    question: "Alin ang tama: 'May/Mayroong'?",
    choices: [
      "Mayroon akong libro.",
      "May akong libro.",
      "Mayroong ako libro.",
      "May libro mayroon ako."],
    answerIndex: 0, explanation: "'Mayroon' + panghalip; 'May' + pangngalan diretso." },

  // ============ READING COMPREHENSION (30) ============
  // English RC passages
  { id: "rc1", subject: "Reading Comprehension", topic: "Main Idea (English)", difficulty: "normal",
    passage: "Coral reefs are among the most diverse ecosystems on Earth. They support nearly a quarter of all marine species despite covering less than 1% of the ocean floor. However, rising sea temperatures and ocean acidification threaten their survival. Scientists warn that without urgent action, many reefs could disappear within decades.",
    question: "What is the main idea of the passage?",
    choices: [
      "Coral reefs are colorful tourist attractions.",
      "Coral reefs are biodiverse but endangered.",
      "Ocean temperatures are rising globally.",
      "Marine species are disappearing quickly."],
    answerIndex: 1, explanation: "The passage centers on biodiversity AND threats — not either alone." },
  { id: "rc2", subject: "Reading Comprehension", topic: "Inference (English)", difficulty: "hard",
    passage: "Coral reefs are among the most diverse ecosystems on Earth. They support nearly a quarter of all marine species despite covering less than 1% of the ocean floor. However, rising sea temperatures and ocean acidification threaten their survival.",
    question: "Which conclusion is best supported?",
    choices: [
      "Reefs are unimportant ecologically.",
      "Reefs are disproportionately important relative to their area.",
      "Most ocean species live outside reefs.",
      "Acidification is the only major threat."],
    answerIndex: 1, explanation: "1% area but 25% of species → disproportionate importance." },
  { id: "rc3", subject: "Reading Comprehension", topic: "Vocabulary in Context (English)", difficulty: "hard",
    passage: "The senator's speech was so verbose that few listeners stayed until the end.",
    question: "In context, 'verbose' most nearly means:",
    choices: ["powerful", "wordy", "silent", "humorous"], answerIndex: 1,
    explanation: "Listeners left → too long/wordy." },
  { id: "rc4", subject: "Reading Comprehension", topic: "Tone (English)", difficulty: "hard",
    passage: "Yet again, the committee delayed its decision — citing, as always, the need for more 'thorough' deliberation. One wonders if any decision will ever arrive.",
    question: "The tone of the passage is best described as:",
    choices: ["enthusiastic", "sarcastic", "neutral", "fearful"], answerIndex: 1,
    explanation: "Quotation marks around 'thorough' and the rhetorical question signal sarcasm." },
  { id: "rc5", subject: "Reading Comprehension", topic: "Author's Purpose (English)", difficulty: "hard",
    passage: "Regular exercise improves cardiovascular health, reduces stress, and enhances cognitive function. Numerous studies confirm these benefits across all age groups.",
    question: "The author's primary purpose is to:",
    choices: ["entertain", "persuade", "inform", "criticize"], answerIndex: 2,
    explanation: "Factual, study-based listing of benefits → informative." },
  { id: "rc6", subject: "Reading Comprehension", topic: "Detail (English)", difficulty: "normal",
    passage: "The Philippine eagle, one of the world's largest eagles, is critically endangered. Fewer than 400 pairs remain in the wild, mostly in Mindanao, Luzon, Samar, and Leyte.",
    question: "Where are most Philippine eagles found?",
    choices: ["Visayas only", "Mindanao, Luzon, Samar, Leyte", "Palawan", "Metro Manila"], answerIndex: 1,
    explanation: "Stated directly." },
  { id: "rc7", subject: "Reading Comprehension", topic: "Inference (English)", difficulty: "hard",
    passage: "Despite years of saving, Mark realized he was no closer to buying a home. Each month, rising rents and unexpected costs ate into his deposit.",
    question: "What can be inferred?",
    choices: [
      "Mark earns a high salary.",
      "Mark is failing to save effectively despite his efforts.",
      "Mark already owns a home.",
      "Mark refuses to budget."],
    answerIndex: 1, explanation: "Saving but not progressing → ineffective despite effort." },
  { id: "rc8", subject: "Reading Comprehension", topic: "Main Idea (English)", difficulty: "hard",
    passage: "Artificial intelligence is reshaping industries, from healthcare diagnostics to logistics planning. While productivity gains are evident, displacement of certain jobs raises ethical concerns. Policymakers must balance innovation with worker protection.",
    question: "The passage primarily argues that:",
    choices: [
      "AI is harmful and should be banned.",
      "AI brings benefits and challenges that require balanced policy.",
      "AI will replace all human jobs.",
      "Policymakers oppose AI adoption."],
    answerIndex: 1, explanation: "Balance between gains and concerns." },
  { id: "rc9", subject: "Reading Comprehension", topic: "Vocabulary (English)", difficulty: "beast",
    passage: "Her stoic demeanor during the crisis surprised everyone; she neither wept nor complained.",
    question: "'Stoic' most nearly means:",
    choices: ["emotional", "unemotional", "fearful", "joyful"], answerIndex: 1,
    explanation: "Did not weep/complain → unemotional." },
  { id: "rc10", subject: "Reading Comprehension", topic: "Logical Structure (English)", difficulty: "hard",
    passage: "First, electric vehicles reduce tailpipe emissions. Second, they lower long-term fuel costs. Finally, they support energy independence by reducing oil imports.",
    question: "How is the passage organized?",
    choices: ["Cause and effect", "Listing of arguments", "Comparison", "Narrative"], answerIndex: 1,
    explanation: "First/Second/Finally signal a list of supporting points." },
  { id: "rc11", subject: "Reading Comprehension", topic: "Inference (English)", difficulty: "hard",
    passage: "Although the road was familiar, Lina drove carefully, glancing repeatedly at her side mirrors and slowing at every intersection.",
    question: "What does the passage suggest about Lina?",
    choices: [
      "She is a reckless driver.",
      "She is unfamiliar with the route.",
      "She is cautious despite knowing the road.",
      "She is in a hurry."],
    answerIndex: 2, explanation: "'Although familiar' contrasts with her cautious behavior." },
  { id: "rc12", subject: "Reading Comprehension", topic: "Main Idea (English)", difficulty: "normal",
    passage: "Reading regularly strengthens vocabulary, improves focus, and broadens perspective. Even fifteen minutes a day yields measurable benefits.",
    question: "The passage is mostly about:",
    choices: ["why books are expensive", "the benefits of regular reading", "famous authors", "writing techniques"], answerIndex: 1,
    explanation: "All sentences support reading benefits." },
  { id: "rc13", subject: "Reading Comprehension", topic: "Tone (English)", difficulty: "hard",
    passage: "It is, regrettably, a pattern we have seen too many times: promises made in haste, broken at leisure.",
    question: "The tone is:",
    choices: ["hopeful", "disappointed", "indifferent", "celebratory"], answerIndex: 1,
    explanation: "'Regrettably' and 'broken at leisure' express disappointment." },
  { id: "rc14", subject: "Reading Comprehension", topic: "Detail (English)", difficulty: "normal",
    passage: "Solar panels convert sunlight into electricity through photovoltaic cells. The efficiency of modern panels ranges from 15% to 22%.",
    question: "What is the maximum efficiency mentioned?",
    choices: ["15%", "20%", "22%", "25%"], answerIndex: 2, explanation: "Stated directly: up to 22%." },
  { id: "rc15", subject: "Reading Comprehension", topic: "Inference (English)", difficulty: "beast",
    passage: "Every great empire eventually overextends. Resources thin, borders fray, and complacency at the center grows. History rarely makes exceptions.",
    question: "The author implies that:",
    choices: [
      "Empires last forever.",
      "Decline of great powers is virtually inevitable.",
      "Resources are unlimited.",
      "Borders should be expanded indefinitely."],
    answerIndex: 1, explanation: "'History rarely makes exceptions' = near-inevitability." },

  // Filipino RC
  { id: "rc16", subject: "Reading Comprehension", topic: "Pangunahing Ideya (Filipino)", difficulty: "normal",
    passage: "Ang wikang Filipino ay patuloy na yumayabong sa paglipas ng panahon. Naghahalo rito ang mga salita mula sa Espanyol, Ingles, at iba't ibang katutubong wika sa bansa, na nagpapakita ng dinamikong kalikasan ng ating wika.",
    question: "Ano ang pangunahing ideya ng talata?",
    choices: [
      "Mabagal lumago ang Filipino.",
      "Patuloy na yumayabong at dinamiko ang Filipino.",
      "Mas mahalaga ang Ingles kaysa sa Filipino.",
      "Walang impluwensya ang ibang wika."],
    answerIndex: 1, explanation: "Tinukoy ang paglago at impluwensya — dinamiko ang wika." },
  { id: "rc17", subject: "Reading Comprehension", topic: "Detalye (Filipino)", difficulty: "normal",
    passage: "Ang wikang Filipino ay patuloy na yumayabong. Naghahalo rito ang mga salita mula sa Espanyol, Ingles, at iba't ibang katutubong wika sa bansa.",
    question: "Aling wika ang HINDI binanggit?",
    choices: ["Espanyol", "Ingles", "Hapon", "Katutubong wika"], answerIndex: 2,
    explanation: "Hindi binanggit ang Hapon." },
  { id: "rc18", subject: "Reading Comprehension", topic: "Hinuha (Filipino)", difficulty: "hard",
    passage: "Sa kabila ng mahabang araw ng trabaho, hindi nawawalan ng ngiti si Aling Marta sa kanyang mga suki. Para sa kanya, ang bawat kostumer ay parang kapamilya.",
    question: "Ano ang masasabi tungkol kay Aling Marta?",
    choices: [
      "Madamot siya.",
      "Mabait at masaya kahit pagod.",
      "Hindi siya gusto ng mga suki.",
      "Tamad siya."],
    answerIndex: 1, explanation: "Hindi nawawalan ng ngiti = mabait kahit pagod." },
  { id: "rc19", subject: "Reading Comprehension", topic: "Damdamin (Filipino)", difficulty: "hard",
    passage: "Tahimik na umupo si Pedro sa tabing-dagat, pinagmasdan ang paglubog ng araw. Walang sinabi, ngunit ang luha sa kanyang mga mata ay malinaw na nagsasalita.",
    question: "Anong damdamin ang ipinapakita ng talata?",
    choices: ["Galit", "Lungkot", "Tuwa", "Takot"], answerIndex: 1,
    explanation: "Luha at katahimikan = lungkot." },
  { id: "rc20", subject: "Reading Comprehension", topic: "Talasalitaan (Filipino)", difficulty: "hard",
    passage: "Ang kanyang masinop na pamamahala ang dahilan ng tagumpay ng kumpanya.",
    question: "Ano ang kahulugan ng 'masinop' sa talata?",
    choices: ["maluho", "maingat at organisado", "malungkot", "malakas"], answerIndex: 1,
    explanation: "Sa konteksto ng pamamahala: maingat, organisado." },
  { id: "rc21", subject: "Reading Comprehension", topic: "Layunin ng May-akda (Filipino)", difficulty: "hard",
    passage: "Mahalagang pangalagaan ang ating mga kagubatan. Sila ang nagbibigay ng oksiheno, tubig, at tirahan sa libu-libong species. Ang pagkawala nila ay magdudulot ng matinding sakuna.",
    question: "Ano ang layunin ng may-akda?",
    choices: ["Mag-aliw", "Magpaalala/manghikayat", "Magbenta", "Mang-insulto"], answerIndex: 1,
    explanation: "Hinihikayat ang mambabasa na pangalagaan ang kagubatan." },
  { id: "rc22", subject: "Reading Comprehension", topic: "Pangunahing Ideya (Filipino)", difficulty: "normal",
    passage: "Sa panahon ng pandemya, naging mahalaga ang teknolohiya sa pag-aaral. Sa kabila ng mga hamon, marami ang natutong umangkop at gamitin ito nang mabuti.",
    question: "Ano ang pangunahing ideya?",
    choices: [
      "Walang silbi ang teknolohiya.",
      "Mahalaga ang teknolohiya at marami ang umangkop.",
      "Madaling matuto online.",
      "Tapos na ang pandemya."],
    answerIndex: 1, explanation: "Mahalaga + umangkop ang mga estudyante." },
  { id: "rc23", subject: "Reading Comprehension", topic: "Detalye (Filipino)", difficulty: "normal",
    passage: "Ang Pilipinas ay may mahigit 7,000 isla at 175 wika. Ito ay isa sa pinakamayamang bansa sa kultura at biodiversity sa Timog-Silangang Asya.",
    question: "Ilan ang wika sa Pilipinas ayon sa talata?",
    choices: ["100", "175", "200", "7,000"], answerIndex: 1, explanation: "Tinukoy: 175 wika." },
  { id: "rc24", subject: "Reading Comprehension", topic: "Hinuha (Filipino)", difficulty: "hard",
    passage: "Bagamat malaki ang kinikita ni Mang Tonyo, kapos pa rin sila sa pang-araw-araw. Hindi siya marunong magbadyet at madalas magbili ng hindi kailangan.",
    question: "Bakit kapos sila kahit malaki ang kita?",
    choices: [
      "Mababa ang sahod.",
      "Hindi marunong mag-budget at maluho.",
      "Maraming anak.",
      "Mahirap ang trabaho."],
    answerIndex: 1, explanation: "Direktang sinabi: hindi marunong mag-budget." },
  { id: "rc25", subject: "Reading Comprehension", topic: "Tono (Filipino)", difficulty: "hard",
    passage: "Muli na namang ipinagpaliban ang proyekto. Tila walang katapusan ang mga dahilan ng pamahalaan.",
    question: "Anong tono ang ipinakikita?",
    choices: ["pagkasabik", "pagkadismaya", "pagsang-ayon", "pagkamangha"], answerIndex: 1,
    explanation: "'Muli na namang' at 'walang katapusan ang dahilan' = dismaya." },
  { id: "rc26", subject: "Reading Comprehension", topic: "Pangunahing Ideya (Filipino)", difficulty: "hard",
    passage: "Ang edukasyon ay susi sa pag-unlad. Hindi lang ito pagbabasa at pagsulat — kasama rin ang paghubog ng pagkatao, kakayahang mag-isip nang malalim, at pagiging mapanagot na mamamayan.",
    question: "Ano ang pangunahing ideya?",
    choices: [
      "Edukasyon ay tungkol lang sa libro.",
      "Edukasyon ay malawak at pundasyon ng pag-unlad.",
      "Mahirap ang edukasyon.",
      "Hindi mahalaga ang edukasyon."],
    answerIndex: 1, explanation: "Malawak na pagtingin sa edukasyon bilang susi ng pag-unlad." },
  { id: "rc27", subject: "Reading Comprehension", topic: "Detalye (Filipino)", difficulty: "normal",
    passage: "Si Lola Conching ay 80 taong gulang ngunit aktibo pa rin sa pagtatanim ng gulay. Araw-araw, bago sumikat ang araw, nasa hardin na siya.",
    question: "Anong oras nagsisimulang magtanim si Lola Conching?",
    choices: ["tanghali", "hapon", "bago sumikat ang araw", "gabi"], answerIndex: 2,
    explanation: "Direktang nakasaad sa talata." },
  { id: "rc28", subject: "Reading Comprehension", topic: "Hinuha (Filipino)", difficulty: "beast",
    passage: "Bawat tagumpay ni Maria ay sinasalubong ng masamang tingin ng ilan niyang katrabaho. Lalo siyang pinupuri ng amo, lalong tumitindi ang malamig na pakikitungo sa kanya.",
    question: "Ano ang hinuhang damdamin ng mga katrabaho?",
    choices: ["pagmamalaki", "inggit", "pagmamahal", "pagkasabik"], answerIndex: 1,
    explanation: "Masamang tingin habang pinupuri ang iba = inggit." },
  { id: "rc29", subject: "Reading Comprehension", topic: "Layunin (Filipino)", difficulty: "hard",
    passage: "Iwasan ang labis na asin sa pagkain. Ito ay maaaring magdulot ng mataas na presyon ng dugo at sakit sa puso.",
    question: "Ano ang layunin ng talata?",
    choices: ["mang-aliw", "magpapayo/magpaalala", "magbenta ng pagkain", "purihin ang asin"], answerIndex: 1,
    explanation: "Pagpapayo tungkol sa kalusugan." },
  { id: "rc30", subject: "Reading Comprehension", topic: "Pangkalahatang Pag-unawa (Filipino)", difficulty: "hard",
    passage: "Ang bayanihan ay tradisyon ng pagtutulungan ng mga Pilipino. Mula sa pagbubuhat ng bahay hanggang sa pagtulong sa kapitbahay sa oras ng pangangailangan, ipinapakita nito ang ating diwa ng pagkakaisa.",
    question: "Aling pangungusap ang HINDI tama batay sa talata?",
    choices: [
      "Ang bayanihan ay tradisyon ng pagtutulungan.",
      "Ipinapakita ng bayanihan ang pagkakaisa.",
      "Ang bayanihan ay nawala na sa kultura.",
      "Maaaring maipakita ang bayanihan sa pagtulong sa kapitbahay."],
    answerIndex: 2, explanation: "Hindi sinasabi ng talata na nawala na ang bayanihan." },
];

export const SUBJECTS = [
  "Mathematics",
  "Science",
  "English Language",
  "Filipino Language",
  "Reading Comprehension",
] as const;
